### ISSUE TITLE
Implement `--before`, `--then`, `--else` flags

### ISSUE THREAD

**Issue by f-f** [purescript/spago#1005]
They are useful and documented, but not ported yet.

Entrypoint for the implementation is here: https://github.com/purescript/spago/blob/32d89b515e656a57ee78552b87f31cf93d8decdc/src/Spago/Command/Build.purs#L111

There are a lot of tests that are just commented out: https://github.com/purescript/spago/blob/32d89b515e656a57ee78552b87f31cf93d8decdc/test/Spago/Build.purs#L99

**Comment by JordanMartinez** [comment]
Just to further clarify this issue... There are 4 actions: before, primary, then, and else.

In the commented out code here (https://github.com/purescript/spago/blob/master/src/Spago/Command/Build.purs#L80-L81), `then` always runs and `else` runs only when a failure happens. Is that intentional? Or is 'then' supposed to run only when `primary` succeeds and the 'else' runs when `primary` fails?

What actions are included in the `primary` one? Currently, 3 tasks being done here but I'm unsure whether the third one should be included:
- `Psa.compile` - This is included
- Possible alternative backend build - I believe this should be included
- Pedantic packages check - is this included?

**Comment by f-f** [comment]
> Or is then supposed to run only when primary succeeds and the else runs when primary fails?

I think the Haskell implementation has this latter behaviour. [We have tests](https://github.com/purescript/spago/blob/master/test/Spago/Build.purs#L143) (currently commented out) that should be used as an acceptance suite - let's try with this behaviour and see if that's what the original implementation was doing

> What actions are included in the primary one? Currently, 3 tasks being done here but I'm unsure whether the third one should be included

I think it should be included as well? It's part of the build process after all.

**Comment by fsoikin** [comment]
What if `before` fails? I'm guessing the rest should be aborted in that case, right?

**Comment by fsoikin** [comment]
Also: the comments and tests suggest that this is only for `build`. Is that right? What about `bundle`?

**Comment by fsoikin** [comment]
Ohhhh, another question.

At first glance it would appear that `before` is extraneous, since `spago build --before foo` would be equivalent to `foo && spago build`

This suggests to me that there should actually be five stages, not four: `prep`, `before`, `primary`, `then`, `else`

Is that right? If so, what does the `prep` include?

**Comment by f-f** [comment]
Good questions - I think these flags were most useful when spago had a `--watch` flag, so you could approximate a task runner with it. These days I don't see the value of these flags as it's possible to orchestrate a build with `npm run` or `make` just fine.

I'll close this for now; let's reopen it if we find a solid usecase that justifies implementing all of this in Spago instead of relying on existing task runners.

**Comment by fsoikin** [comment]
In that case the docs should be updated, right?

**Comment by f-f** [comment]
Yep - done in 6d2f796
