### ISSUE TITLE
Tag error in spago publish

### ISSUE THREAD

**Issue by Ebmtranceboy** [purescript/spago#1078]
```json
{
  "name": "dual-numbers",
  "ref": "v1.0.1",
  "compiler": "0.15.10",
  "location": {
    "githubOwner": "Ebmtranceboy",
    "githubRepo": "purescript-dual-numbers"
  }
}
```

**Comment by f-f** [comment]
(I have moved this issue to the Spago repository)

**Comment by Ebmtranceboy** [comment]
The  error was

> Your package dual-numbers is not ready for publishing yet, encountered 3 errors:


> ❌ The tag (v1.0.1-1-g95174e3) does not match the expected tag (v1.0.2).
> Please make sure to tag the correct version before publishing.

I just deleted the v1.0.2 tag locally and remotely, and recreated it and that helped. Now, my package is published! Thanks @f-f

**Comment by f-f** [comment]
Great! 👏 

I am puzzled by the `v1.0.1-1-g95174e3` tag - did you make it yourself or did Spago create it?

**Comment by Ebmtranceboy** [comment]
The only tags I created are v1.0.0, v1.0.1 and v1.0.2. This one has been mechanically generated but I don't know by what

**Comment by f-f** [comment]
Uh, this sounds like a bug

**Comment by Ebmtranceboy** [comment]
Since this is also the first time that I use a .yaml file (rather than a .dhall one), let me share something new I've noticed, maybe this is related : until now, I had to declare all the dependencies of my project, even those that were only used for testing (like `purescript-assert`). 

Now, I've noticed that `assert` is not welcome anymore. I had a warning about that. This is coherent and good! 

Since I've even forgotten to mention it in `test: dependencies:` with no warning, I'm wondering if this dependency is implicitly resolved and if a virtual tag is created for that purpose. This may explain the unknown tag reference.

And if not, what is the prescribed way of declaring the testing-exclusive dependencies : should I declare `assert` ?

**Comment by f-f** [comment]
My guess is that `assert` is being pulled in by some other package? Otherwise there would be no reason for it to appear in the build plan. I wish I could suggest just running `spago why`, but that's still work in progress in #732 

And yes, test-only dependencies should go in `package.test.dependencies`. The `test` section also has a `pedantic_packages` key - you can set that to true to have Spago issue warnings for undeclared dependencies

Re the phantom tag: no, we handle tags only when publishing, so it's probably some bug in the pipeline

**Comment by f-f** [comment]
Uh, that's weird. We don't create tags, just ask the user to do that.

We call `git describe --tags` to see if the ref that is currently checked out is a tag, which seems to be quite broken, since it will return a funny tag+commit mashup. I guess we could work with that, but we can probably do better..

**Comment by f-f** [comment]
Ah, it seems we need to add `--exact-match` to that git call. Easy fix! 😄

**Comment by Ebmtranceboy** [comment]
FYI, I can't pass `spago test` without declaring `effect` and `assert`. That's good and answers my question!
Now, to summarize last time, I passed that `spago test` stage with `assert` declared at the wrong place, then removed it, then ran `spago publish` with a non-passing-test project. This may have caused a strange path. Maybe, tests should be run a little later ... I don't know

**Comment by f-f** [comment]
Tests are unrelated, we don't run them when publishing.
