### ISSUE TITLE
How are package_set hashes calculated?

### ISSUE THREAD

**Issue by jeslie0** [purescript/spago#1087]
I am creating a [repository](https://github.com/jeslie0/mkSpagoDerivation) to help package PureScript projects as Nix derivations. I am currently facing an issue with retrieving remote package sets, such one of the [one's listed in Spago's readme](    https://raw.githubusercontent.com/purescript/package-sets/psc-0.15.7-20230207/packages.json). I have have found that Nix disagrees the hash generated by Spago:

For the package set https://raw.githubusercontent.com/purescript/package-sets/psc-0.15.7-20230207/packages.json, Spago calculates the hash as

`sha256-vYZfm1HbZdKistBheZl1sC8nTaQN2usV2rSeq+Wp2vE=`

while Nix (with nix-hash) calculates the hash of the json file as

`sha256-6Pq7g3d6H9hjUNsHlLk3YPK6s1KuQKFQF8gxMugd8n0=`.

(The base 16 hash of the json file corresponds to the output of running `sha256sum` on it).

What is the hash in the spago.yaml file a hash of? Should it be the same as running `sha256sum` on the json file and converting to base 64 with SRI?

**Comment by thomashoneyman** [comment]
The hash doesn't appear to be of the package set file itself but rather of a Spago-defined `PackageSetResult` type:
https://github.com/purescript/spago/blob/726a45ba3784bce6b6b5e61d1e52a74994555fdd/src/Spago/Config.purs#L503-L510

Which is defined here:
https://github.com/purescript/spago/blob/726a45ba3784bce6b6b5e61d1e52a74994555fdd/src/Spago/Config.purs#L484

In any case, the hash wouldn't be of a package set from the `purescript/package-sets` repository because that is only for legacy package sets. It would be the hash of the current package set format, such as this one, which is stored in the registry repository:
https://github.com/purescript/registry/blob/main/package-sets/43.1.0.json

I'm a bit curious as to why Spago defines a `PackageSetResult` type instead of using the registry's `PackageSet` type:
https://github.com/purescript/registry-dev/blob/master/lib/src/PackageSet.purs

But perhaps Spago is performing some more processing (like merging in extra_packages) for their type. In any case, if you're trying to reproduce the hash in Nix, then you're in a bit of trouble because as far as I can tell you don't have direct access to the string that Spago is creating and then hashing.

**Comment by jeslie0** [comment]
Okay! It isn't a deal breaker for me if this doesn't work. Thank you!

**Comment by f-f** [comment]
@jeslie0 yeah hashes of the package sets are not something that we consider a public API at the moment, because we support Nix through the lock files - if you set `lock: true` in your workspace then Spago will produce a lock file which should contain all the information that you need

**Comment by jeslie0** [comment]
I haven't been able to successfully generate a lock file from a spago.yaml yet. [thomashoneyman](https://github.com/thomashoneyman) has provided some resources and examples that I can use for my own development though.

**Comment by f-f** [comment]
@jeslie0 did you stumble on any bug? Or just can't get it to work and we need to improve [the docs](https://github.com/purescript/spago#the-lock-file)?

**Comment by jeslie0** [comment]
@f-f I think I am seeing [this bug](https://github.com/purescript/spago/issues/917#issuecomment-1566291308). Putting `lock: true` in my workspace and running `spago build` or `spago install` doesn't output a lock file for me, with a fresh `spago init` made project (spago version 0.93.14).

**Comment by f-f** [comment]
Oh no, that's pretty broken 😭
