### ISSUE TITLE
Check package boundaries before git tree

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1108]
```
» npx spago publish
Reading Spago workspace configuration...
Read the package set from the registry

✅ Selecting package to build: foldable-traversable-extra

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.

Pushing tag 'v0.0.1' to the remote
Username for 'https://github.com': flip111
Password for 'https://flip111@github.com': 
Your package "foldable-traversable-extra" is not ready for publishing yet, encountered 1 error:


❌ The configuration is missing version bounds for some packages. Run `spago fetch --ensure-ranges` to add them:
  - arrays-extra
  - either
  - foldable-traversable
  - maybe
  - ordered-collections
  - prelude
  - transformers
  - tuples
```

IMO would be better to first check the thing that doesn't require a password.

An example of a failed git tree check looks like this
```
❌ The git tree is not clean, or you haven't checked out the tag you want to publish.
Please commit or stash your changes, and checkout the tag you want to publish.
To create the tag, you can run:
  git tag v0.0.1
```

**Comment by flip111** [comment]
Also when you add ranges you change a local file, and when you already made a tag on an older commit i guess you have to make a new tag

**Comment by f-f** [comment]
Makes sense

**Comment by JordanMartinez** [comment]
It sounds like we want two things here:
- report as many errors at once, so that we don't have to run `spago publish` 6x before all errors are resolved and so we don't need to create a new git tag if such changes will invalidate the current git tag.
- don't request special information (e.g. password) until after we've cleared fixable issues

**Comment by f-f** [comment]
> report as many errors at once

We already do this as much as we can - there might be some things left to optimise, and maybe rearranging things around can help to parallelise more error reporting

> don't request special information (e.g. password) until after we've cleared fixable issues

I think this really comes down to pushing the git tagging as late as possible in the publishing code, so that we only push the tag when we are sure that everything else is fine
