### ISSUE TITLE
Improve accessibility for the generated docs #4519

### ISSUE THREAD

**Issue by jquesada2016** [purescript/spago#1125]
I originally opened this issue [here](https://github.com/purescript/purescript/issues/4519) but I think it actually might belong in this repo?

**Comment by f-f** [comment]
@jquesada2016 I moved your previous issue to https://github.com/purescript/purescript/issues/4519, because the docs are generated by the compiler itself, and Spago is just a thin layer on top. Let's continue the discussion in that thread - there is already some activity there that you might have missed

**Comment by jquesada2016** [comment]
@f-f thank you for pinging me, I definitely missed it!

**Comment by f-f** [comment]
No worries at all - it seems easy to miss things on this website and it happens to me all the time 😄
