### ISSUE TITLE
`spago migrate` ignores `as Location` packages

### ISSUE THREAD

**Issue by wclr** [purescript/spago#1141]
In `packages.dhall` I have:

```dhall
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.15.9-20230718/packages.dhall
      with my-packge =
          ./some-locaton/.my-package/spago.dhall as Location
```

`spago migrate` didn't transfer any of `as Location` package to new `spago.yaml`

**Comment by f-f** [comment]
This is intentional - the new Spago has a different way of thinking about the monorepo situations: you don't include other packages explicitly, but all the packages in the workspace are included by default. This case covered the vast majority of these imports and there's no good heuristic to make sense of those, so we're just stripping it away.

I'd recommend reading about [the monorepo support](https://github.com/purescript/spago#monorepo-support) and about [the Spago "workspace"](https://github.com/purescript/spago#the-workspace) if you haven't already.

I think that all in all we can't do a 100% smooth migration from old configs and it's always going to be a somewhat manual process, even just for sanity check - so the best thing that we could do would be to document thoroughly which parts need manual intervention and how; do you think there's any way to improve the docs?

**Comment by wclr** [comment]
Isn't old config's
```dhall
      with my-packge =
          ./some-locaton/.my-package/spago.dhall as Location
```
the same as

```yaml
my-package:
  path: ./some-locaton/.my-package 
```
in new config?

**Comment by f-f** [comment]
No, you shouldn't have to specify packages that are in your subfolders, they will be picked up by default as parts of your monorepo if they have a `spago.yaml`.

**Comment by wclr** [comment]
> The path syntax is for packages that are outside of your repo, e.g.

To me this is quite strange to have packages directly referenced outside the project's root folder. Usually in such cases the code is still linked (using symlinks for example) in to the project folder to keep it consistent at least virtually. So if I point to the package inside projects forlder it will not work, though I belive there is valid cases for this.

In any case as a user I would prefer to have an option of manual control over which folders should be included and considered as packages, not rely on auto traversing the whole project content, it may be very inificient. There could just be an option that takes a glob pattern of where to expect the packages, and not to perform unnessary search (as pointed in https://github.com/purescript/spago/issues/1140).

**Comment by f-f** [comment]
> maybe different cases why uncontrolable traversing though the project content may lead to unpredictable results

Sure, and we have encountered [some](https://github.com/purescript/spago/issues/1100) of [those](https://github.com/purescript/spago/issues/918) in the past, and fixed them. I'm sure we can do something about them once we have enough information to diagnose the issue.

**Comment by f-f** [comment]
Anyhow, I'd like to have some more clarification on the initial point of this issue, could you please address that?

> I think that all in all we can't do a 100% smooth migration from old configs and it's always going to be a somewhat manual process, even just for sanity check - so the best thing that we could do would be to document thoroughly which parts need manual intervention and how; do you think there's any way to improve the docs?

**Comment by f-f** [comment]
@wclr I will close this issue since it looks like the initial issue has been clarified. Let's reopen it once we have some concrete improvement idea for the docs
