### ISSUE TITLE
spago upgrade does not clean old dependencies

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1143]
I had a folder `.spago/packages/arrays-7.2.1` then i ran upgrade and a new folder appeared `arrays-7.3.0` so far so good. But the old folder `.spago/packages/arrays-7.2.1` was not removed even though that no longer matches with the project. Because in the project `spago.yaml` the `registry` value was increased.

I think removing the old folder would be the preferred case for most situations. I only see it being useful in case you are offline (train / airplane) and you also want to swap back to the old registry. Though I'm not sure if swapping back to the old registry is possible when you are offline.

**Comment by f-f** [comment]
> But the old folder `.spago/packages/arrays-7.2.1` was not removed even though that no longer matches with the project. 

As a general principle Spago tries to not remove files, [as that might lead to trouble](https://www.theregister.com/2015/01/17/scary_code_of_the_week_steam_cleans_linux_pcs/). If the build still works then we are not going to change this behaviour - cleaning old files is left as a responsibility of the user, since all the content of `.spago` is just a cache anyways so it can be safely deleted.

**Comment by flip111** [comment]
finding old dependencies by hand and deleting them one by one takes a lot of time for a user

**Comment by f-f** [comment]
@flip111 `rm -rf .spago` is just a few characters?

**Comment by flip111** [comment]
ye ok i guess you won't upgrade the package set too often. So then it's upgrade, remove cache, rebuild
