### ISSUE TITLE
Change on lock file re-compiles everything

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1150]
This is probably not so easy to implement and i guess not first priority either. But it would be nice if the lock file changes that not everything gets recompiled but only those dependencies who had their versions changed.

**Comment by f-f** [comment]
This is not about the lockfile, but rather due to how purescript compilation works - if Module B depends on Module A and Module A changes, then Module B will be recompiled. Spago is not doing much here, just asking the compiler to rebuild, and it's a process we don't control.

This issue is known in the compiler repo as "build cutoff", and quite some effort is going into fixing it, see this for the latest attempt: https://github.com/purescript/purescript/pull/4477

**Comment by f-f** [comment]
I'll close because this is behaviour is normal, but let's reopen if you find a case where it doesn't look right

**Comment by flip111** [comment]
Let's close it yes. Thanks for the link to the purescript compiler issue
