### ISSUE TITLE
Option to opt out of CLI emoji via spago.yaml, env var, and/or flag

### ISSUE THREAD

**Issue by toastal** [purescript/spago#1183]
I appreciate the effort & whimsy put into selecting + supporting emojis, and I like them on websites & in chats, & I can get down with ASCII art or Kaomoji (｡•̀ᴗ-)✧ or general Unicode, I however find emoji in terminal output with its bright colors and solid fills distracting in the visual hierarchy for both TUI workflows & reading my logs; it’s too much. Emoji will also appear broken in TTYs, other environments, & cases where the system emoji doesn’t support the chose symbol.

Considering there’s a way to opt out of color, I would like to opt out of emoji.

Yarn v1 (JS) uses `yarn --no-emoji `or in the RC file `{ ..., emoji: false }`. Homebrew for macOS uses `HOMEBREW_NO_EMOJI=1`. Babel (JS) & Ember (JS) ended up removing their emoji support from CLI altogether.

**Comment by f-f** [comment]
The emojis are not for cuteness, but for clarity of display - I put them there to grab attention in key parts of the build, e.g. see here, they appear (1) when selecting the package to build and (2) when the build is done:

<img width="607" alt="image" src="https://github.com/purescript/spago/assets/5480361/94e99dcd-2166-4768-b372-c84f05b5826a">

So the idea is exactly what you are mentioning, to get your attention while you read logs.
I personally find they look great on my terminal, but YMMV as other OSs have different emoji packs.

This is all to say that while I'm not happy about adding yet another flag, I'm up for swapping them out if we find another way of grabbing attention in the same way.

I guess we could just disable them when `--no-color` is passed? This would solve the issue of them being broken on TTYs as well, since we default to no-color there.

**Comment by f-f** [comment]
The screenshot above is from Kitty FWIW

**Comment by f-f** [comment]
Ah indeed that doesn't look good. The only emojis that we use are ❌ and ✅ and ⚠️, we can switch them out for equivalent Unicode symbols if we can find ones that approximate these well.

**Comment by f-f** [comment]
Cool, we can go for `✔`, `⚠` and `✖`, and skip them if we are running with `no-color` (since TTY won't support that either)

**Comment by fsoikin** [comment]
I found a bit of a problem with these non-emoji characters. For some reason, in Windows Terminal, they look like this:

![image](https://github.com/user-attachments/assets/17e74cbc-26b3-4ae3-8d0a-df62f389ac9c)

Note how they smush into the text. This is not because I neglected to add a space. They actually require _two_ spaces.

In fact, even if I just paste them in the command line they behave the same:

![winterm-cross](https://github.com/user-attachments/assets/081d6c13-01e0-4347-8a45-f6fdb0120968)

-------------------

This appears to be an issue with the newer generation Windows UI, because they also look like this in the historic clipboard UI:

![image](https://github.com/user-attachments/assets/3e179bc7-cd3e-4472-bb7d-71ca28246bbb)

But they look normal in GNOME Terminal:

![image](https://github.com/user-attachments/assets/36ae3baa-ad06-4d09-808d-b46d240c5d3c)

As well as in ConEmu, which uses Win32 UI:

![image](https://github.com/user-attachments/assets/c989d00a-d2d3-4cad-98cb-bdcb0e893997)

I cannot verify on a Mac.

--------------------

So this is only an issue for Windows, but I'm unsure what the official policy on this would be here.

**Comment by fsoikin** [comment]
Checking some of the other checkmark characters:

Windows Terminal:
![image](https://github.com/user-attachments/assets/a7c89b30-188f-4277-a574-81aeda794dc7)

GNOME Terminal:
![image](https://github.com/user-attachments/assets/5ba9262a-d390-4e34-81bd-7ec97948baa1)

ConEmu:
![image](https://github.com/user-attachments/assets/2036ae2c-4aeb-477d-9436-715cf3eff853)

The only stable one appears to be `\x2713` - "light checkmark".

**Comment by f-f** [comment]
Of course, Unicode joys 😄

I'd say let's try to find a set of characters that look good in Windows/Gnome, and I can test them on mac.

We can try using the 2713 checkmark, and other things that don't render weirdly.
In case it still looks unreasonable we can special-case Windows of course.

**Comment by fsoikin** [comment]
A wide variety of crosses is available.

Windows Terminal:
![image](https://github.com/user-attachments/assets/f8a01498-5f02-4d25-a3a0-add30f5abea3)

GNOME Terminal:
![image](https://github.com/user-attachments/assets/3c5e09bc-f329-455c-a303-91acfe46ccbc)

ConEmu:
![image](https://github.com/user-attachments/assets/0af531bb-919b-43c7-92cc-a48db4ec10d0)

**Comment by fsoikin** [comment]
On "warning" signs, however, the choice is extremely limited.

Windows Terminal:
![image](https://github.com/user-attachments/assets/66ab2ddf-c564-40df-9aab-0dba8fa3948e)

GNOME Terminal:
![image](https://github.com/user-attachments/assets/37ac0f3f-c9cb-4957-969b-8e3110d1d3fe)

ConEmu:
![image](https://github.com/user-attachments/assets/6c4b3a6d-d4d2-4093-a29c-bcc9aa12ca01)

**Comment by fsoikin** [comment]
We might also do ASCII art instead, like:

![image](https://github.com/user-attachments/assets/0ff6dc2c-e294-4df0-9905-3d637ec63c75)

Or: 
![image](https://github.com/user-attachments/assets/7a654dff-cf9a-4e3a-b91e-eea53715e190)

**Comment by f-f** [comment]
Thanks for collecting these - let's try to use 2713 for the checkmark, 2718 for the cross, and 26A0 for the warning sign.

I'd also say let's leave them in in monochrome mode, because Unicode support may be present even when opting out of color. Worst case one will get the unicode replacement block, which is alright.

**Comment by fsoikin** [comment]
The 26A0 character is essentially the same emoji I think. Or at least it has similar problems.

Windows Terminal:
![image](https://github.com/user-attachments/assets/95862200-fc5f-4776-929a-ad83fca0ef88)

GNOME:
![image](https://github.com/user-attachments/assets/c0fecff9-f9ae-41a7-a2ff-2bbf99981899)

ConEmu (note the shift):
![image](https://github.com/user-attachments/assets/b1415beb-fe0c-4f12-868c-2b1f3d2a3864)

What's the argument against ASCII art?

**Comment by f-f** [comment]
> What's the argument against ASCII art?

The `[v]` looks confusing to me - the other ones are fine.

> The 26A0 character is essentially the same emoji I think. Or at least it has similar problems.

Right. 203C is our next best bet. If that doesn't work I'm tempted to just stick with the emojis 😅

**Comment by fsoikin** [comment]
Done. 203C looks acceptable from my POV.
