### ISSUE TITLE
spago@next installation fails on windows

### ISSUE THREAD

**Issue by mendrik** [purescript/spago#1185]
moduleNotFoundError: No module named 'distutils'. If I read it right distutils has been removed in latest python installtion and therefor fails the spago installation.

**Comment by f-f** [comment]
How is python related to spago? Are you installing through npm?

**Comment by mendrik** [comment]
I think on windows it tries to install / run node-gyp which requires python to be installed. so a newbie installs newest python so npm i spage@next works, and it fails because discutils is not automatically installed with python any longer. Docs could at least hint at what is required for the npm command to work, maybe?

**Comment by f-f** [comment]
I'd expect npm to just work tbh. Are you on the latest node/npm?

**Comment by mendrik** [comment]
```
C:\Desk> node --version
v21.1.0
C:\Desk> npm --version
10.2.0
```

more or less

**Comment by f-f** [comment]
I see - [a quick search shows](https://stackoverflow.com/questions/77251296/distutils-not-found-when-running-npm-install) that this is really a temporary environmental issue due to python 3.12 deprecating a previously common package. I don't think we should be documenting this ourselves since it's about a dependency of npm - I'd expect it to be fixed upstream (either already or soon) so it will go away with an upgrade to the toolchain.
