### ISSUE TITLE
"dest already exists" error

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1206]
I have this repo https://github.com/flip111/purescript-barlow-lens I'm getting the following error

```
» spago test
Reading Spago workspace configuration...

✅ Selecting package to build: barlow-lens

Cloning https://github.com/purescript/purescript-arrays.git
file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:61132
                  throw util.fromLeft(step3);
                  ^

Error: dest already exists.
    at doRename (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:10603:15)
    at moveSync4 (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:10588:14)
    at file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:94011:56
    at runSync (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60789:21)
    at run16 (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60982:25)
    at file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60998:23
    at drain (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60816:9)
    at Object.enqueue (file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60834:11)
    at file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:60992:31
    at file:///home/flip111/.nvm/versions/node/v21.7.1/lib/node_modules/spago/bin/bundle.js:90717:30

Node.js v21.7.1
```

**Comment by f-f** [comment]
This should not happen - we explicitly check that `dest` doesn't exists
https://github.com/purescript/spago/blob/9e83d87b01b01a7e03ae46efc171daa7caa7140f/src/Spago/Command/Fetch.purs#L388
before moving the repo in its place:
https://github.com/purescript/spago/blob/9e83d87b01b01a7e03ae46efc171daa7caa7140f/src/Spago/Command/Fetch.purs#L363

What are the contents of `.spago/p/arrays`?

**Comment by flip111** [comment]
I had remove the repo locally, so i had to clone it again. Thus old cache was no longer there. Also i updated spago to `0.93.28`. With these changes the problem does not occur anymore. I will reopen if it happens again and then show the contents  of `.spago/p/arrays`

**Comment by naufalauddin** [comment]
I got a similar issue when running [`spago install` on gitlab CI](https://gitlab.com/naufalauddin/deku-playground/-/jobs/7875583412) even though it worked fine [before](https://gitlab.com/naufalauddin/deku-playground/-/jobs/7873913991). Here is [one with verbose on](https://gitlab.com/naufalauddin/deku-playground/-/jobs/7876345464)

On my machine, If I remove `.spago` directory, only the first run of `spago install` has the problem, the next `spago install` seems to just fixed itself.

I assumed it was because both `deku-core` and `deku-dom` has the same repository, both passed the check before trying to move the pulled repo, and only of them succeeded. On the next run, since the repo already exist, it skipped moving the repo to the same location. Though, I don't know why it worked before.

Since gitlab CI didn't cache `.spago` dir if an error occured, I'm stuck with the error for my CI.

**Comment by naufalauddin** [comment]
I've recreated a minimal example of the issue at https://gitlab.com/naufalauddin/purescript-depends-on-two-module-same-repo

**Comment by f-f** [comment]
Thanks @naufalauddin! I can repro the issue locally, it's definitely a bug

**Comment by f-f** [comment]
Ah I see the issue here - we got a race condition! When the lockfile is up to date then spago can fetch all dependencies in parallel, here:
https://github.com/purescript/spago/blob/6d2f7966339ad4e62e76c5782eae0ad1360f78ec/src/Spago/Command/Fetch.purs#L207

We then get these log lines:
```
[     118ms] Downloading dependencies...
[     119ms] Cloning repo in /var/folders/8s/2w_ybl6s0qd_xzmklw4pkscm0000gn/T/spago-nodejs/506970654977434337636148425050374c7477745a6c5371773d
[     119ms] Cloning https://gitlab.com/naufalauddin/dummy-purescript-module.git
[     121ms] Cloning repo in /var/folders/8s/2w_ybl6s0qd_xzmklw4pkscm0000gn/T/spago-nodejs/645238354b4d74396867696d344d5a68614f4b47454d4a37673d
[     121ms] Cloning https://gitlab.com/naufalauddin/dummy-purescript-module.git
```

So we are cloning the same repo twice, which is not supposed to happen (as per #1275). We'll need to do some sort of deduplication here so that we only clone once.
