### ISSUE TITLE
use pathy

### ISSUE THREAD

**Issue by srghma** [purescript/spago#1292]
Suggestion: to improve type safety :)

1. implement windows parser https://github.com/purescript-contrib/purescript-pathy/issues/19#issuecomment-507287291
2. finish https://github.com/srghma/purescript-pathy-node-fs/blob/main/src/Pathy/Node/FS/Common.purs
3. use in spago

**Comment by srghma** [comment]
maybe use glob from https://github.com/purescript-node/purescript-node-fs/pull/86

**Comment by f-f** [comment]
We're implementing stronger-typed paths in #1296 - these are custom types, made to fit the codebase, which should give the same assurances as using something like Pathy but better UX. I'll close this since I think that's the better approach, but we'll reopen it if we decide not to go with custom types
