### ISSUE TITLE
Use dependency of dependency when package is not in package set

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1299]
When i want to use this library as dependency of my project https://github.com/srghma/purescript-tidy-codegen/blob/main/spago.yaml

i get
```
» spago run --backend-args '--help'
Reading Spago workspace configuration...

✓ Selecting package to build: html2halogen

Cloning https://github.com/srghma/purescript-tidy-codegen.git

✘ The following packages do not exist in your package set:
  - dodo-printer
  - tidy (did you mean: tldr, midi)
```

Since these packages are not in the package set can spago not just use the specified git repos, this one for example? https://github.com/srghma/purescript-tidy-codegen/blob/main/spago.yaml#L62 seems a bit redundant that i have to copy this manually into my spago.yaml file

**Comment by f-f** [comment]
That would entail reading the `workspace` section of the dependencies - there are a few issues with that and we're likely not going to implement it:
- the format for that section might change and we don't guarantee compatibility - we already read the `package.dependencies` key today, and _that_ is guaranteed to stay stable because the Registry depends on it
- the package set for your current package becomes less declarative and more indirect, if we had this you would have to climb an unspecified amount of repos to reconstruct your package set, which goes against the self-contained nature of package sets
- ultimately the version that you might fetch from there might be fine for the upstream library that you're using but might not be the right one for your project. We can't know that beforehand so we avoid any automation in this regard

**Comment by flip111** [comment]
I try to understand what you wrote.

> * the format for that section might change and we don't guarantee compatibility

Does it mean parts of the configuration format is stable and others are not? Might this change in the future with for example configuration scheme versions with possible backwards compatibility?

> * you would have to climb an unspecified amount of repos

Wouldn't it be specified in the configuration files of the dependencies? I mean you would know how many lookups there are when you start looking it up, if that sounds problematic i guess a hardlimit with spago flag as override could be used?

> * which goes against the self-contained nature of package sets

I don't understand the nature of package sets. All i know is from my previous experience with other programming languages (npm/js and haskell to know a few) which will just fetch dependencies of dependencies. Maybe you can explain some benefits of package sets? I'm not understanding what we are winning here

> * but might not be the right one for your project

In case you decide to use the same package for your project as a direct dependency. And on top of that use a different version. Wouldn't it be obvious that there is a version conflict due to it being a different branch or different commit? I mean git is supposed to tell you what version you are on so it should be able to see if two copies of the same repository are on the same version or not. If there is a version conflict at that point there shouldn't be any further automation IMO. You can just leave it to the user to go fix that. I'm familiar with this mechanism with, for example, cabal. But i know that other programming languages also have a package manager that can point to conflicting dependencies. What further did you have in mind to automate here?

**Comment by f-f** [comment]
> Does it mean parts of the configuration format is stable and others are not? Might this change in the future with for example configuration scheme versions with possible backwards compatibility?

It's more like a guarantee that some key parts of the config won't ever change. We won't guarantee the whole schema, otherwise we wouldn't be able to ever change anything.
If we do change something we'll try to keep backwards compatibility, and have schema migrations.

> Wouldn't it be specified in the configuration files of the dependencies? I mean you would know how many lookups there are when you start looking it up, if that sounds problematic i guess a hardlimit with spago flag as override could be used?

Lookups are not the issue. The issue is about not having all the information in a single place that is easily accessible and debuggable. If we'd do this automatically and your package wouldn't build as a result of one of these transitive dependencies being broken, we would have to report the whole chain of dependencies, etc. Feels like it would be a worse UX.

> Maybe you can explain some benefits of package sets? I'm not understanding what we are winning here

I have written about it [in the docs](https://github.com/purescript/spago?tab=readme-ov-file#whats-a-package-set). To summarise, package sets are similar to lockfiles, but more generic in the sense that a project might (and most often will) choose to only use a subset of the package versions listed there.

**Comment by f-f** [comment]
I feel like the discussion is focusing on using spago as a tool to pull in git repositories - the scope that we cover is much bigger than that, and honestly I don't think I should personally spend time polishing the UX for that.
If someone else wants to come up with a proposal about improving the UX of this particular usecase together with an implementation sketch, then we can talk about the merits of that specific solution, and the maintenance burden that merging it will entail.

Spago is a package manager for PureScript, and as that it serves one particular customer with more attention than the rest: the Registry and its packages.
Handling git packages in the context of build plans is supported but not particularly pleasant (as you noticed), which is partly because of the reasons I laid out in my previous comment, and partly because it's supposed to nudge you to publish packages to the Registry.

In fact, I don't particularly follow why you're set on using git repos for everything: to follow the example packages you mentioned in the first post, `dodo-printer` is already in the registry, and the other one could be easily added.

If using git repos is particularly important for other reasons and you need to do this over several repos (as it is the case e.g. when using custom backends), then using a [custom package set](https://github.com/purescript/spago?tab=readme-ov-file#custom-package-sets) is another valid option.

**Comment by flip111** [comment]
> it serves one particular customer with more attention than the rest: the Registry and its packages.

i definitely agree with this statement. IMO it's wonderful to have a cohesive package set that works together

> then we can talk about the merits of that specific solution

ok that's cool !

> I don't particularly follow why you're set on using git repos

sometimes major packages don't release new versions (for various reasons which are not interesting to get into IMO). I saw this several times. One example is this https://github.com/purescript-web/purescript-web-dom/commits/master/

The last release is from Apr 28, 2022 about 2.5 years ago. When i want to use commits from a year ago i can not use the package set from the registry.

> it's supposed to nudge you to publish packages to the Registry

i understand the intent, sometimes people are busy or they don't want to publish for some reasons even when you ping them (that didn't happen in the given example, but on other occasions). It's just how it is i guess.

**Comment by f-f** [comment]
> I definitely agree with this statement. IMO it's wonderful to have a cohesive package set that works together

Package sets are convenient, but that's not what I mean when I refer to registry packages: you can use packages from the registry without using a package set at all, and indeed that's the recommendation if you're developing a library.

> The last release is from Apr 28, 2022 about 2.5 years ago. When i want to use commits from a year ago i can not use the package set from the registry.

I can cut a release for that. Would you help me with [filling the rest of the changelog](https://github.com/purescript-web/purescript-web-dom/blob/master/CHANGELOG.md)?

**Comment by flip111** [comment]
Great! Here is the updated changelog https://github.com/purescript-web/purescript-web-dom/pull/60

What about adding a spago.yaml to that package?
