### ISSUE TITLE
`docs --project-only`

### ISSUE THREAD

**Issue by thought2** [purescript/spago#577]
Currently there's the `--deps-only` flag, which generates documentation only for the dependencies of a project and not for the project sources itself. But isn't it more common that you'd like the opposite?

**Comment by f-f** [comment]
@thought2 how would this work? It's not possible to compile docs without including dependencies - because the compiler needs to typecheck/etc so you need the whole dependency tree. A solution could be to compile with everything but then remove the docs related to dependencies - but this would leave us with lots of broken links pointing to the non-existing files, so this doesn't work either.

My guess for why such a feature would be desiderable is that it's hard to find the project docs in the sea of docs from the dependencies, right?

If that's so, I think a more viable idea to alleviate the problem could be to implement [module grouping as proposed here](https://github.com/spacchetti/purescript-docs-search/issues/20) (note: we have `purescript-docs-search` as an overlay to the html docs generated by the compiler, so we can patch things there). We could even go further and once we have the mapping (which is necessary to introduce the logic to group modules to packages), then we could lift the project packages on top of the package list so that they're easy to reach

**Comment by thought2** [comment]
Yeah right, the actual problem is to 'find the project docs in the sea of docs'. I'll close and add some thoughts in the linked issue.
