### ISSUE TITLE
`$ spago run` runs cached version of `Main` module if one is not found instead of throwing an error

### ISSUE THREAD

**Issue by danny-andrews** [purescript/spago#621]
I ran into some strange behavior with `$ spago run` today. It looks like if it can't find a module named `Main`, it will use some cached version from a previous build.

STR:
1. Create Main.purs with some code.

```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "hello"
```

2. Rename the Main module to something else:

```purescript
module Blah where

import Prelude
import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "goodbye"
```

3. Run `$ spago run`

Expected: Receive an error indicating that spago could not find a module named `Main`
Actual: It runs fine without error, and outputs "hello" to the console.

 I don't know if this is intended or not, but I found it pretty surprising! It's like spago was running some ghost code or something. I discovered this behavior because I copied and pasted some example code into Main.purs, but the module was named `RandomExample` and so the code in it was ignored by `$ spago run`.

Cheers!

**Comment by JordanMartinez** [comment]
I don't think this is an issue with spago. Rather, I assume that you wrote your original `Main.purs` file that exposed `main` and then built it via `spago build` and then replaced its contents with something else. In such a case, your `output` folder is still referring to the old state, so when `spago run` is called, which calls `purs`, it thinks that it doesn't need to rebuild Main, which then means it doesn't discover that there is no more Main anymore.
I believe this is fixed in the purescript compiler's master branch and will be included in the next release.

**Comment by hdgarrood** [comment]
I don’t think it is fixed; I’m not sure we would even consider this a bug (although it is definitely surprising). The compiler won’t  ever delete modules in the output directory, it just overwrites them when you edit them. I am reasonably confident that some people (maybe many) find this behaviour useful. For example, suppose you have an app with a backend and frontend component and some shared code between them, where the client is in `client/`, the server is in `server/`, and code used by both components is in `src`. Then you might list `src/` in your sources (but not `client/` or `server/`) in spago.dhall, and your build command might be `spago bundle-app —path client —to client.js && spago bundle-app —path server —to server.js`. If you run that command twice in a row, the second time, with the way it works now, nothing needs to be recompiled. However if we were to start deleting modules from `output` if they don’t correspond to source files passed to the most recent invocation, you’d have to rebuild all of `client/` and `server/` each time you ran that command, because building the client would remove all of the cached server build products, and then building the server would remove all of the cached client build products.

**Comment by hdgarrood** [comment]
In any case this is indeed not an issue with spago, it’s to do with how the compiler works.

**Comment by JordanMartinez** [comment]
Ah, good point @hdgarrood! I had forgotten about that situation.

**Comment by danny-andrews** [comment]
Cool, that makes sense. If you get into that spot, do can you just delete output and rebuild everything?

**Comment by danny-andrews** [comment]
Yeah, that seems to work. Thanks for the info, y'all.

**Comment by JordanMartinez** [comment]
Yup.
