### ISSUE TITLE
Should `spago run` emit build log information to stdout?

### ISSUE THREAD

**Issue by athanclark** [purescript/spago#623]
Hello, I have somewhat of a cosmetic question - when running `spago run` on a fresh project, it needs to compile all of the modules before running the actual application.

When `spago build` is run, I would expect that output to go straight to stdout - that information is first class from that command's perspective. However, I'm proposing that the build data from `spago run` should be emitted to stderr, or something that wouldn't be piped when redirecting output - because you're _only_ trying to get the command output. Interestingly, the output from spago itself (i.e. `[info] Build succeeded.`) _is_ actually sent to stderr, so that's where I'm somewhat confused.

I hope this helps the pursuit to robust build tools :)

**Comment by f-f** [comment]
Hi @athanclark! Yes, we're aware of this problem, and it's been [reported upstream](https://github.com/purescript/purescript/issues/3672). It will be fixed in version `0.14.0` of the compiler, PR [here](https://github.com/purescript/purescript/pull/3839)

So I'll close this issue as it's already being taken care of, but let's reopen if we figure out there's anything more we need to do about this
