### ISSUE TITLE
Spago bundle-app requires config in 0.15 version

### ISSUE THREAD

**Issue by Nimor111** [purescript/spago#634]
Hello, 

After upgrading the version of `spago` in my project to 0.15.2 where I use the `bundle-app` command it started failing with the following error:

```
[error] Failed to read the config. Error was:
[error] There's no "spago.dhall" in your current location.
```
This does not happen in version 0.14.0.

Poking around the code a bit, I found that in version 0.15 the command has the following line: 
https://github.com/purescript/spago/blob/0.15.2/app/Spago.hs#L89

Which has a call to `Run.withBuildEnv` which as far as I can trace the code boils down to this:
https://github.com/purescript/spago/blob/0.15.2/src/Spago/RunEnv.hs#L72

Which requires a `spago.dhall` to be present.

While in 0.14.0, it seems to not require a `spago.dhall`:
https://github.com/purescript/spago/blob/0.14.0/app/Spago.hs#L441

Is this intentional? 

Some more details about my setup:
I am using `spago2nix` and running the command with the following flags:
`spago bundle-app --no-install --no-build --main Main --to dist/app.js`

Thanks in advance!

**Comment by f-f** [comment]
Thanks for reporting this and for noting the details about your setup - it seems like you found a "nice" corner case.

The answer to your question is that this was "sort of intentional": this breakage happened in https://github.com/purescript/spago/pull/610 where we restructured the "runtime environments" to clarify their requirements (e.g. "needs purs", "needs git", "needs a valid config")

You can see here that `bundle-app` is invoked in a `BuildEnv`:

https://github.com/purescript/spago/blob/8c44f1c149f6a41df45931ec05f361742b31cd1c/app/Spago.hs#L90-L91

Which makes sense because if we need to install&build we need that. Except if we pass `--no-build` (as you did), which skips all of that and just bundles - see line 255:

https://github.com/purescript/spago/blob/8c44f1c149f6a41df45931ec05f361742b31cd1c/src/Spago/Build.hs#L250-L255

So, this is a bug and we should take note of how the `no-build` flag affects the requirements of the code
