### ISSUE TITLE
spago --version also prints help text

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/spago#649]
`spago version` prints the version number whereas `spago --version` prints the version number followed by three blank lines and the full help text.

Is this intended?

**Comment by f-f** [comment]
If you look at [the PR where I introduced this](https://github.com/purescript/spago/pull/628) you'll see that I did notice. However it's not really intended, as I just took the lazy route of just using [`optionsExt`](https://www.stackage.org/haddock/lts-16.1/turtle-1.5.19/Turtle-Options.html#v:optionsExt) from Turtle.
I guess we'd like the two commands to behave the same?
If yes, I suspect that we could reuse some of the code from Turtle, or just code this from `optparse-applicative`

**Comment by ozkutuk** [comment]
I have given a quick look, it seems that Turtle is using `infoOption` from `optparse-applicative` to add the version flag. However, it also uses [`prefShowHelpOnError`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#t:ParserPrefs) in its configuration which causes help message to be displayed on parse errors. Since [`infoOption`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:infoOption) is an option that always fails by design, help message is shown whenever `--version` is used.

I couldn't think of a straightforward solution to this, since I think "help on error" option useful, but there is no other "intended" way to display a message other than `infoOption`. TBH I don't think the current behavior is too problematic, but having a uniform display would certainly be nice.

**Comment by f-f** [comment]
I just realized that Dhall is able to do this:

```
$ dhall version
1.32.0

$ dhall --version
1.32.0
```

The secret on how to do it is [somewhere in this module](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/Main.hs) (they are using plain `optparse-applicative` for everything)
