### ISSUE TITLE
Feature request: spago init chooses most recent package set compatible with available compiler

### ISSUE THREAD

**Issue by bbarker** [purescript/spago#657]
To demonstrate the problem when running `spago init`:

```
installed `purs` version:    0.13.6
minimum package-set version: 0.13.8
There are a few ways to solve this:
- install a compatible `purs` version (i.e. in the same 'semver range' as the one in the package set)
- if the `purs` version is 'too new', you can try using `spago upgrade-set` to upgrade to the latest package set
- if you know what you're doing and you want to avoid this check, you can override the `version` of the `metadata` package in the packages.dhall:
  let overrides = { metadata = upstream.metadata // { version = "v0.13.6" } }
```

As at it happens 0.13.6 is currently the most recent version in nixpkgs. There are workarounds, but I'll argue that this is more problematic for certain cases, such as the one I have: A training server with some interactive materials, that I would like to leave up without monitoring. However, I just noticed that the exercises no longer work, since each time a user runs an exercise for Purescript, `spago init` is called under the hood.

An alternative that could also fix the problem but have distinct pros and cons might be to allow a parameter specifying the package set to be used with `spago init`.

**Comment by f-f** [comment]
Yeah this is something we should do. We could just do it the way that `psc-package` does it, by just querying the compiler version and picking the first set available for that, see https://github.com/purescript/package-sets/issues/647

**Comment by hdgarrood** [comment]
If we implement picking the most recent package set compatible with the current compiler, that presumably has the additional benefit of allowing `spago upgrade-set` to work for people who are not on the latest version of the compiler, since we could have `spago upgrade-set` use the same logic. For example, if I'm using purs 0.12.x and I run `spago upgrade-set`, then it would be nice if spago were able to pick the latest package set compatible with 0.12.x (even though there are already a bunch of released package sets compatible with 0.13.x).

I think we could achieve this either by fetching all of the releases on the package-sets repo, parsing the compiler version and date out, and working out what the most recent compatible set is that way, or by storing a mapping of compiler versions to latest compatible package sets in the package-sets repository and fetching that file from Spago. @f-f do you have a preference? There are already 127 releases on the package-sets repo and that's only going to increase over time, so I think a putting this information in a file in the package-sets repo would probably be simpler overall and more future-proof, and it may be useful for other tools too.

**Comment by f-f** [comment]
@hdgarrood great points. My preference goes for storing a mapping between compiler version and "latest compatible package set" in the `package-sets` repo, so that we don't have to hit the GitHub API at all

**Comment by f-f** [comment]
Idea for an implementation strategy: when trying to figure out a new set to use (i.e. when doing `init` and `upgrade-set`) we should try the following options in this order:
- if we were passed a `--set` flag, we should just use that set
- if not, then we try fetching [this file](https://github.com/purescript/package-sets/blob/master/latest-compatible-sets.json) to lookup which version we should use (according to the current compiler version), then try to use that version
- ...if fetching the file fails _or if using the new set fails_ (this is a failure scenario because old sets might be missing from the release page, or be malformed, or whatever. This might fail) then we should just fallback to use the set `psc-${compiler-version}`, that it's always guaranteed to be there (it's the first set we release for every compiler version)
