### ISSUE TITLE
Potentially out of date documentation.

### ISSUE THREAD

**Issue by lukasturcani** [purescript/spago#658]
Thank you very much for the useful tool.

In the readme, in the "Publish my library" section, one of the steps is 

"use pulp publish (so it's available on the Bower registry and on Pursuit)"

I believe that this is not applicable to new libraries, which need to use the `pulp publish --no-push` command, as running `pulp publish` will lead to the following error " EUNKNOWN Unknown error: 500 - Registering bower package names is not supported anymore. You can install any bower package on github with command like "bower install jquery/jquery-dist --save"

**Comment by f-f** [comment]
@lukasturcani I believe the latest `pulp` has fixed this and will prompt you to add the library to the registry before pushing? Could you verify this?

**Comment by lukasturcani** [comment]
I updated pulp to version `15.0.0`, purs is `0.13.8` and spago is `0.15.2`.
On an existing library, where I've previously successfully ran `pulp publish --no-push` I now get 
```
Checking your package is registered in purescript/registry... 
* No package with the name purescript-mol-draw exists in the registry.
* Please register your package by sending a PR to purescript/registry first, adding your package to `new-packages.json`
* ERROR: Package not registered
```

With both `pulp publish` and `pulp publish --no-push`, after running `spago bump-version --no-dry-run 1.0.12 `, where `1.0.12` is a valid version number for my project.

**Comment by f-f** [comment]
@lukasturcani thank you for doing this, it seems like it's working as it should - the current situation is transitional and unfortunately not as polished as it could be, but that's because we are mostly working to move past the transition, and polish that end of things. So I'll close this issue, but let's reopen if I misinterpreted your last sentence and you think Spago's documentation could be improved somehow.

**Comment by lukasturcani** [comment]
Thank you as well! 

No, I think spago's documentation is very good at the moment, my comment was just referring to the fact since a PR is required before publishing, the spago documentation could mention that need. However, since this requirement is transitional, and because the error message is very clear, I personally don't think changes to the documentation are necessary at this point.

**Comment by jiyinyiyong** [comment]
Feeling a bit confused while following the docs to publish my library, spago, pulp, purescript/registry, package-sets, bower, so much places to check. Since this is an issue from last year, is the current docs the final version or it's still waiting to be polished for a final one?

**Comment by f-f** [comment]
@jiyinyiyong it's still not in a polished state, sorry for that. Would you have any suggestions on how to improve docs in this regard?

**Comment by jiyinyiyong** [comment]
@f-f not really. some context... I previously came from Nim, and Nim uses [a repo of json](https://github.com/nim-lang/packages) for the list of packages as well. And I only have to publish package to one place(to the JSON file in the repository) for one time, then I can just run `<pkg-manager> install` to use it. So at first it's quite confusing to me I have to interact with 3 places to registry a package.

I noticed it mentioned somewhere that the packages was migrating after Bower stopped accepting new packages. Has the migration finished yet? Do I still have to interact with multiple registries in the end? I wonder the confusions may mostly came from the tools rather than the docs.

**Comment by f-f** [comment]
Thanks for the explanation. The migration is not completed yet but we're working on this. You can find a summary of where we are [here](https://github.com/purescript/registry#implementation-plan)
