### ISSUE TITLE
Add flag to skip local cache

### ISSUE THREAD

**Issue by elliotdavies** [purescript/spago#660]
We already have a flag to skip the global cache (e.g. `--global-cache=skip`) when running commands but it would be handy to have one for the local `.spago` cache too so that I don't have to `rm -rf .spago` when I'm messing about with my project's dependencies.

This would particularly apply to `spago install` and `spago build`, but it would probably be fine as a global flag to mimic `--global-cache`.

**Comment by hdgarrood** [comment]
Could you explain in a bit more detail about how you are messing about with your project's dependencies? I haven't ever come across a situation where I've needed to do `rm -rf .spago`.

**Comment by elliotdavies** [comment]
The use case I bumped into was pretty much like [this one](https://github.com/purescript/spago#override-a-package-in-the-package-set-with-a-remote-one) from the README. I'll concede it's not an ideal way to work 😄

**Comment by hdgarrood** [comment]
Right, but `spago build` should only pick up the version specified by your packages.dhall, even if there are other versions in your `.spago` directory, right? The only way I can see that being a problem is if you're using a glob like `.spago/**/src/**/*.purs`, but in that case I would say it's the glob that's the problem, and you ought to be able to fix that by using `spago sources` instead, I think?

**Comment by f-f** [comment]
Indeed, if you're pinning to a commit or a tag then there should be no need to fiddle with the `.spago` folder. Yes, you *could* point to a branch and have to remove `.spago` when that gets updated, but why not point to a commit hash in the first place?

I'm not sure we should encourage this kind of use-cases, so I'll close this issue for now, but let's reopen if it turns out I misunderstood what we're trying to achieve here :slightly_smiling_face:

**Comment by elliotdavies** [comment]
I found another potential use for this today when debugging the issue with `purescript-money`, which was accidentally deleted from Github and so broke the package set. (It's now been restored.) In order to reproduce and solve the issue locally I needed to run `spago install` a bunch of times after bypassing both the global and local caches. I could use `--global-cache=skip` for the former but for the latter I could only `rm -rf .spago`.

**Comment by f-f** [comment]
Thanks for the report. I'm starting to think that maybe we should not have a local cache at all, but just point the compiler to the paths in the global cache.

This might be fine for most of the things - some complications that come to mind are:
- this might be annoying for caching things in CI, where caching the `.spago` directory could be easier than caching the global cache. This can be worked around by pointing the global cache to `.spago`, but this should be documented well.
- right now we use the local cache when packages refer to branches, so we'd have to either forbid branches or keep the local cache just for that.
  This usecase is also useful for people that want to patch git repos in place in the local cache, which is a workflow I've seen

**Comment by hdgarrood** [comment]
I'm not sure getting rid of the local cache is the way to go. What should happen if you have two separate projects with separate package sets in which there is a package `foo`, where project A's packages.dhall says `foo` is hosted at `user-a/purescript-foo`, and project B's packages.dhall says `foo` is hosted at `user-b/purescript-foo`, and they both have a tag `v1.0.0` but are different at that tag? It's harder to see how to support that properly without reworking how the global cache works. I feel like it's probably safer to only globally cache things if they are in a centralized registry, so that there can't be any doubt about what they refer to.
