### ISSUE TITLE
spago build not working on Windows via WSL

### ISSUE THREAD

**Issue by jamievicary** [purescript/spago#678]
I'm on spago 0.15.3, but still having trouble with issue #644. I'm running inside an Ubuntu WSL instance within Windows 10.

In my project I can execute "purs", and the executable is correctly located. But when I execute "spago build", I get the response:

    [error] Executable was not found in path: "purs"

The verbose output is not much more help:

````
2020-08-13 12:53:28.816788: [debug] Running `getGlobalCacheDir`
@(src/Spago/RunEnv.hs:44:7)
2020-08-13 12:53:28.826451: [debug] Transformed config is the same as the read one, not overwriting it
@(src/Spago/Config.hs:364:14)
2020-08-13 12:53:29.131066: [debug] Ensuring that the package set is frozen
@(src/Spago/PackageSet.hs:275:3)
2020-08-13 12:53:29.375115: [error] Executable was not found in path: "purs"
@(src/Spago/Prelude.hs:127:13)
````

**Comment by f-f** [comment]
@jamievicary thanks for reporting! I'm going on vacation soon so I'll be away from my Windows machine for around a month, thus I won't be able to try this out. cc @stkb: do you have any ideas on this?

One thing that comes to mind is: what happens if we instead try to call `purs.exe`? Would that work?

**Comment by thomashoneyman** [comment]
Related: I've just realized that the Windows test for `setup-purescript` isn't actually executing a build -- [the logs for the latest integration test](https://github.com/purescript-contrib/setup-purescript/runs/991020744) show a 0s runtime and no output for the 'spago build ...' command. So that's a reproduction in another environment.

**Comment by f-f** [comment]
@thomashoneyman how do we know that it's a reproduction of this issue and not another issue? I'm a bit confused for the fact that we don't see the same error message

And do you think we could use the action to debug this failure?

**Comment by stkb** [comment]
@jamievicary Are you using WSL 1 or 2? Is your `purs` binary the windows version (.exe) or a linux one?

Off the top of my head, it may be that while the WSL terminal will find/run the windows `purs` binary, Spago doesn't, since under WSL it's a linux platform

**Comment by thomashoneyman** [comment]
@f-f I’m not sure it’s a reproduction of this issue, as the windows machines in GH Actions probably aren’t using WSL. I just connected the “Windows” part of the report 😬

As far as the error — I haven’t actually seen errors out of that Windows console even when the executable for something is missing. Always just says that the command exited.

**Comment by f-f** [comment]
It looks like we are unable to reproduce this, so I'll close for now. Let's reopen if we get more info or some way to reproduce reliably
