### ISSUE TITLE
Feature request: spago script

### ISSUE THREAD

**Issue by Unisay** [purescript/spago#683]
I'd :heart:  to have an analog of `stack`'s script feature:
https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter
https://www.fpcomplete.com/haskell/tutorial/stack-script/#running-a-script

Example:
```sh
$ head myscript.ps
```
outputs:
```purescript
#!/usr/bin/env spago
-- spago script
import Prelude
...
```
then
```sh
$ chmod u+x myscript.ps
$ ./myscript.ps
```

**Comment by klntsky** [comment]
The obvious problem are node.js dependencies (spago does not manage them).

I guess it's possible to write a tiny wrapper over npm (built-in into spago) that would handle them. Would be cool!

**Comment by f-f** [comment]
@klntsky we'll start dealing with "install NPM dependencies" once we switch to the new registry (which keeps track of these), so I'd say it's fine to add them here.

We already have the flag `--dependency` in `spago repl` which we could reuse here, and we could just introduce a `--npm-dependency` flag here to deal with NPM stuff.

However, a first implementation of this feature should not care about NPM stuff at all and just do the PureScript side of things - which I suspect it would solve 80% of the usecases anyways

**Comment by ozkutuk** [comment]
I have been trying my hand at this, but I am not sure how I can go on with interpreting the script. Is compiling to a temporary directory and running it immediately a sensible way to approach this? I couldn't think of any other way, given the options `purs` executable offers.

**Comment by f-f** [comment]
The other day in the FP slack I described this feature as "`spago repl` in a temp folder + adding the script to the sources + `spago run`". A bit more formally:

For the first iteration I would skip the whole thing about interpreting the shebang in files (as proposed in the first post), and concentrate on getting the following to work:
```
spago script --tag psc-13.8-etcetc -d prelude -d effect myscript.purs
```

This would:
- create a new project in a temp dir, where we eventually set the package set to the requested one, and eventually pulled the specified dependencies. Note that we have _all_ the machinery to do this for when `spago repl` is called outside of a project, except for the `--tag` flag, which is handled in `spago init` and `spago upgrade-set`, so it should be easy to pull in
- then we compile this temp project with its normal sources, while adding also the current location of the script to them
- then we call `spago run` on this temp project 

Note: it might be very slow to create a new project for every invocation of `spago script`. So maybe we can create a local `.spago` directory that contains a folder for this project (so not a temp one), based on something like "the hash of the parameters passed to the command" (i.e. the set, the dependencies, the script name) so that we can reuse the project on subsequent invocations if only the script changes

@ozkutuk does this make sense?

**Comment by ozkutuk** [comment]
Sorry for the late response. I have waited until I had a deeper look into the code, but was unable to spare the time required. Despite that, I have understood the approach you describe. I am not working on this for the time being, but I will post an update when I could spare the effort to pick this up again.

**Comment by f-f** [comment]
@ozkutuk no worries and thank you for the update!

**Comment by JordanMartinez** [comment]
Just FYI. https://github.com/purescript/purescript/pull/4214 will likely be getting merged soon.
