### ISSUE TITLE
Confusion about backend

### ISSUE THREAD

**Issue by mitchellwrosen** [purescript/spago#691]
Hi there,

I tried using the `"backend"` key to point at a fork of `purs`, but it doesn't behave as I expect. When running `spago -v build`, I see:

```
[debug] Running `getGlobalCacheDir`
[debug] Transformed config is the same as the read one, not overwriting it
[debug] Ensuring that the package set is frozen
[debug] Running `spago build`
[debug] Getting transitive deps
[debug] Running `fetchPackages`
[debug] Checking if `purs` is up to date
[debug] Compiling with "purs"
[debug] Running command: `purs compile --codegen corefn ".spago/console/v4.4.0/src/**/*.purs" ".spago/effect/v2.0.1/src/**/*.purs" ".spago/prelude/v4.1.1/src/**/*.purs" ".spago/psci-support/v4.0.0/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"`
[info] Build succeeded.
[debug] Compiling with backend "my-purs-fork"
[debug] Running command `my-purs-fork`
```

... and then the build fails because `my-purs-fork` is expecting some arguments. It seems like there might be two things wrong, but I'm not sure:

1. Should `spago` be running `purs`, even with an alternative backend set?
2. Should `spago` be providing `my-purs-fork` with a list of `.purs` files to compile?

Thanks!

**Comment by f-f** [comment]
The `backend` key is really made only for alternate backends, where the compilation flow is different from compiling with the standard backend.
With an alternate backend you first need to compile with `purs --codegen corefn` to get the CoreFn output, that then the backend takes and compiles down to the target language. You normally don't have to worry about any of that because Spago automates it.

Since the compilation procedure is different this doesn't work if you just want to try out a fork of the compiler. Spago is going to use whatever `purs` executable it finds in the path, so I'd suggest just pointing your `PATH` variable to your fork.
E.g. if you have a `purs` binary (note that it needs to have that exact name) in a folder called `my-purs-fork`, then you can have Spago pick that up in this way:

    PATH="$(pwd)/my-purs-fork:${PATH}" spago build

**Comment by f-f** [comment]
I believe the initial concerns have been addressed here so I'll close for now, but feel free to reopen if I missed something!
