### ISSUE TITLE
Integrate psa into Spago

### ISSUE THREAD

**Issue by f-f** [purescript/spago#904]
Since the upcoming Spago will be in PureScript, we now have the occasion of integrating `psa` directly [as a library](https://github.com/natefaubion/purescript-psa-utils), which is strictly better than the current situation of shelling out to an external executable.

**Comment by JordanMartinez** [comment]
I'm going to work on this, but this is low priority.

**Comment by JordanMartinez** [comment]
Here's a few questions that came to mind as I was looking at this:
- Is the codebase of `purescript-psa-utils` going to be folded into `spago` in its entirety? Or are we just going to depend on that as another dependency? I'd prefer the former because there's less dependency management than the latter (e.g. "If I change X in `purescript-psa-utils`, does it cause issues in `spago`?"). However, if one wanted to implement another package manager besides spago, such an author would likely want to reuse the psa libraries to implement similar features, at least until this functionality is folded into the compiler itself.
    - Depending on the above answer, [`purescript-psa`](https://github.com/natefaubion/purescript-psa/issues) and [`purescript-psa-utils`](https://github.com/natefaubion/purescript-psa-utils/pulls) have either open issues/PRs. When integrating it into this codebase, do we want to account for those issues/PRs as well? One that strikes me in particular is https://github.com/natefaubion/purescript-psa-utils/pull/10, which would have made the `Semigroup`/`Map` warning less annoying.

**Comment by arrowd** [comment]
A bit of offtopic, but what is rationale behind rewriting Spago in PureScript? This will make packaging it harder for downstream packagers.

**Comment by f-f** [comment]
@arrowd I have detailed a bit about it [here](https://github.com/purescript/spago/issues/842#issuecomment-1262935534), but I'll expand more on it once we announce the first alpha release of the rewrite.
Our main packaging method is `npm`, which will benefit from the switch. Is there any particular downstream packager you are concerned about?

**Comment by arrowd** [comment]
I **am** that downstream packager - I make ports for FreeBSD. Wehave nica machinery for Haskell packages that allows us to prefetch all needed deps' sources and build offline. AFAIK, it is not possible for `npm`.

For `purescript-language-server` I had to ask @nwolverson to provide self-contained compiled .js files on the releases page.

**Comment by f-f** [comment]
It sounds like we could reuse that machinery to achieve the same result here?
