### ISSUE TITLE
Support esbuild plugins

### ISSUE THREAD

**Issue by flip111** [purescript/spago#915]
I would like to use this plugin https://github.com/evanw/esbuild/issues/1051#issuecomment-806325487 so that i can use `canvas` which is a dependency of `jsdom`. I've read here under [Using the build API](https://blog.logrocket.com/getting-started-esbuild/), that one should start esbuild through node in this case.

I looked in the spago code if it was possible

https://github.com/purescript/spago/blob/master/src/Spago/Build.hs#L421

doesn't look like it because `esbuild` seems to be hardcoded (after the esbuild binary has been located).

Perhaps we can add a flag `--build-script=/path/to/myscript.js` if that flag is activated it just runs `node /path/to/myscript.js`? The flag would override both purs or esbuild and leave it to the user to make a proper build script ..

**Comment by f-f** [comment]
The support for `spago bundle` right now is definitely best-effort, i.e. we provide just a think opinionated wrapper on top of a simple `esbuild` call, mostly for convenience of use in small projects.

I'm not sure we should add more extensive support and customisability to this, given that most of the time a complex-enough JS bundle step would not go through Spago anyways, but one would have a separate build script take care of things.

And this is would I would recommend doing in this case - instead of calling `spago bundle --build-script=myscript.js` why not just call `./myscript.js`?

**Comment by flip111** [comment]
I was using `bundle-app` and i was under the impression that spago did more than just start esbuild. If it is doing more work, what are the before and after steps of the esbuild program start ?

**Comment by f-f** [comment]
The only "before" step is `spago build`, and there are no after steps.

**Comment by flip111** [comment]
Seems reasonable just to use esbuild directly. Thanks for discussion
