### ISSUE TITLE
Configure backend compile arguments

### ISSUE THREAD

**Issue by nwolverson** [purescript/spago#921]
Alternate backends must support certain command line options to allow `spago` to call them. They may themselves have a need or see the opportunity to expose others, it would be desirable to be able to configure them in the same way we can configure `purs` or run-time options.

Proposed flag: `--backend-compile-args` (@f-f suggestion)

`spago.yaml` option: `backend_compile_args`

Content: Literal compile args as list of strings, to be provided on the command line to the backend after those arguments already supplied by `spago`

**Comment by f-f** [comment]
Fixed in https://github.com/purescript/spago/commit/fcfc5acd411ac7e8bd4097d98f3dcc97dfdd9ceb

There's now a `--backend-args` flag to pass compile-time args to the backend (where `--purs-args` is to pass compile-time args to the compiler, and `--exec-args` to pass runtime args), and an equivalent `workspace.backend.args` option in the config.
